// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	pgx_google_uuid "github.com/vgarvardt/pgx-google-uuid/v5"
)

type User struct {
	ID           pgx_google_uuid.UUID
	Email        string
	Username     string
	PasswordHash string
}
