// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"

	pgx_google_uuid "github.com/vgarvardt/pgx-google-uuid/v5"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, username, email
) VALUES (
  $1, $2, $3
)
RETURNING id, email, username
`

type CreateUserParams struct {
	ID       pgx_google_uuid.UUID
	Username string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Username, arg.Email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgx_google_uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const editUser = `-- name: EditUser :execrows
UPDATE users 
SET username = $1, email = $2
WHERE id = $3
`

type EditUserParams struct {
	Username string
	Email    string
	ID       pgx_google_uuid.UUID
}

func (q *Queries) EditUser(ctx context.Context, arg EditUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, editUser, arg.Username, arg.Email, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUsers = `-- name: GetUsers :many
SELECT id, email, username FROM users
ORDER BY username
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Email, &i.Username); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
