// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"

	pgx_google_uuid "github.com/vgarvardt/pgx-google-uuid/v5"
)

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgx_google_uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}
