// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package database

import (
	"context"

	pgx_google_uuid "github.com/vgarvardt/pgx-google-uuid/v5"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  id, username, email
) VALUES (
  $1, $2, $3
)
RETURNING id, email, username
`

type CreateUserParams struct {
	ID       pgx_google_uuid.UUID
	Username string
	Email    string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.ID, arg.Username, arg.Email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.Username)
	return i, err
}
