openapi: 3.1.0
info:
  title: ElytraMC API
  version: 1.0.0
  description: The ElytraMC API
servers:
  - url: http://localhost:9000
    description: Development server

paths:
  /users:
    $ref: "./../features/user/getUser/openapi.getUser.yaml"
