operationId: createUser
summary: Create user
description: Create one user
requestBody:
  required: true 
  content:
    application/json:
      schema:
        type: object
        properties:
          username:
            type: string
          email:
            type: string
        required:
          - username
          - email
responses:
  "201":
    description: User creation
    content:
      application/json:
        schema:
          type: object
          properties:
            id:
              type: string  
            username:
              type: string
            email:
              type: string
        example: 
          id: e4efa860-92e1-4802-ad96-98b6bba00ce1
          username: Salam
          email: salam@gmail.com
