operationId: deleteUser
summary: Delete user
description: Delete one user
parameters:
  - in: path
    name: id
    schema:
      type: string
    required: true
    description: UUID of the user to be deleted
responses:
  "204":
    description: User successfully deleted, no content returned
  "404":
    description: User not found
